// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyrieetebfzmgffxecpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cmllZXRlYmZ6bWdmZnhlY3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjUzMjUsImV4cCI6MjA2ODgwMTMyNX0.CsRKGWid5IzIEIBSArkg99fEoDiXDQ8zHfRuQVEgtCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});