import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { 
  Share2, 
  ExternalLink, 
  GraduationCap,
  MapPin,
  Calendar,
  Settings2,
  Image as ImageIcon,
  FileText,
  Palette,
  Loader2
} from 'lucide-react';

interface PublicDirectorySettingsProps {
  academyId: string;
}

// Función para convertir nombre a slug
const generateSlugFromName = (name: string): string => {
  if (!name) return '';
  
  return name
    .toLowerCase()
    .trim()
    // Normalizar caracteres especiales (á -> a, é -> e, etc.)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    // Reemplazar espacios y caracteres especiales por guiones
    .replace(/[^a-z0-9]+/g, '-')
    // Eliminar guiones al inicio y final
    .replace(/^-+|-+$/g, '')
    // Limitar longitud
    .substring(0, 50);
};

export const PublicDirectorySettings: React.FC<PublicDirectorySettingsProps> = ({ academyId }) => {
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  
  // Branding Settings
  const [brandColor, setBrandColor] = useState('#1976d2');
  const [secondaryColor, setSecondaryColor] = useState('#42a5f5');
  const [tagline, setTagline] = useState('');
  const [academySlug, setAcademySlug] = useState('');
  const [companyName, setCompanyName] = useState('');
  const [publicDirectoryEnabled, setPublicDirectoryEnabled] = useState(true);
  
  // Directory Settings
  const [showLogo, setShowLogo] = useState(true);
  const [showDescription, setShowDescription] = useState(true);
  const [studentsFilter, setStudentsFilter] = useState<'all' | 'graduated' | 'enrolled'>('all');
  const [updatingDirectory, setUpdatingDirectory] = useState(false);
  
  // Academy Data
  const [academyData, setAcademyData] = useState<any>(null);
  const [graduates, setGraduates] = useState<any[]>([]);

  useEffect(() => {
    loadAllSettings();
  }, [academyId]);

  // Load graduates when filter changes
  useEffect(() => {
    if (academyData) {
      loadGraduates();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [academyId, studentsFilter, academyData]);

  const loadAllSettings = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('companies')
        .select('name, logo_url, description, brand_color, secondary_color, academy_tagline, academy_slug, public_directory_enabled, directory_settings')
        .eq('id', academyId)
        .single();

      if (error) throw error;

      if (data) {
        // Branding settings
        setBrandColor(data.brand_color || '#1976d2');
        setSecondaryColor(data.secondary_color || '#42a5f5');
        setTagline(data.academy_tagline || '');
        setCompanyName(data.name || '');
        
        const savedSlug = data.academy_slug || '';
        const autoGeneratedSlug = generateSlugFromName(data.name || '');
        setAcademySlug(savedSlug || autoGeneratedSlug);
        setPublicDirectoryEnabled(data.public_directory_enabled ?? true);
        
        // Directory settings
        setAcademyData(data as any);
        if (data.directory_settings && typeof data.directory_settings === 'object' && !Array.isArray(data.directory_settings)) {
          const dirSettings = data.directory_settings as { show_logo?: boolean; show_description?: boolean; students_filter?: 'all' | 'graduated' | 'enrolled' };
          setShowLogo(dirSettings.show_logo ?? true);
          setShowDescription(dirSettings.show_description ?? true);
          setStudentsFilter(dirSettings.students_filter ?? 'all');
        }
      }
    } catch (error) {
      console.error('Error loading settings:', error);
      toast.error('No se pudieron cargar las configuraciones');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveBranding = async () => {
    try {
      setSaving(true);
      const { error } = await supabase
        .from('companies')
        .update({
          brand_color: brandColor,
          secondary_color: secondaryColor,
          academy_tagline: tagline.trim() || null,
          academy_slug: academySlug.trim() || null,
          public_directory_enabled: publicDirectoryEnabled,
        })
        .eq('id', academyId);

      if (error) throw error;

      toast.success('Configuración de marca guardada exitosamente');
      // Reload settings to get updated slug
      await loadAllSettings();
    } catch (error) {
      console.error('Error saving branding settings:', error);
      toast.error('No se pudo guardar la configuración de marca');
    } finally {
      setSaving(false);
    }
  };

  const updateDirectorySettings = async (
    show_logo: boolean, 
    show_description: boolean, 
    students_filter: 'all' | 'graduated' | 'enrolled'
  ) => {
    try {
      setUpdatingDirectory(true);
      const { error } = await supabase
        .from('companies')
        .update({
          directory_settings: {
            show_logo,
            show_description,
            students_filter
          }
        } as any)
        .eq('id', academyId);

      if (error) throw error;
      toast.success('Configuración del directorio actualizada');
    } catch (error) {
      console.error('Error updating directory settings:', error);
      toast.error('Error al actualizar configuración del directorio');
    } finally {
      setUpdatingDirectory(false);
    }
  };

  const handleToggleLogo = async (checked: boolean) => {
    setShowLogo(checked);
    await updateDirectorySettings(checked, showDescription, studentsFilter);
  };

  const handleToggleDescription = async (checked: boolean) => {
    setShowDescription(checked);
    await updateDirectorySettings(showLogo, checked, studentsFilter);
  };

  const handleStudentsFilterChange = async (filter: 'all' | 'graduated' | 'enrolled') => {
    setStudentsFilter(filter);
    await updateDirectorySettings(showLogo, showDescription, filter);
  };

  const loadGraduates = async () => {
    try {
      const { data, error } = await supabase.rpc('get_public_academy_directory', {
        p_academy_id: academyId,
        p_status_filter: studentsFilter
      });

      if (error) throw error;
      setGraduates(data || []);
    } catch (error) {
      console.error('Error loading graduates:', error);
    }
  };

  const publicUrl = academySlug || academyData?.academy_slug
    ? `${window.location.origin}/academy/${academySlug || academyData?.academy_slug}`
    : `${window.location.origin}/academy/${academyId}`;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(publicUrl);
    toast.success('Link copiado al portapapeles');
  };

  const handleViewPublic = () => {
    if (!academySlug && !academyData?.academy_slug) {
      toast.error('Configura el slug de la academia primero');
      return;
    }
    window.open(publicUrl, '_blank');
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Directorio Público</h2>
          <p className="text-muted-foreground">
            Configura y personaliza tu directorio público de estudiantes
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={handleCopyLink}>
            <Share2 className="h-4 w-4 mr-2" />
            Copiar Link
          </Button>
          <Button variant="outline" onClick={handleViewPublic}>
            <ExternalLink className="h-4 w-4 mr-2" />
            Ver Directorio
          </Button>
        </div>
      </div>

      {/* Section 0: Habilitar Directorio Público */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Share2 className="h-5 w-5" />
            Directorio Público Habilitado
          </CardTitle>
          <CardDescription>
            Activa o desactiva la visibilidad pública de tu directorio de estudiantes
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between rounded-lg border p-4">
            <div className="space-y-0.5">
              <Label htmlFor="publicDirectory" className="text-base font-medium">
                {publicDirectoryEnabled ? 'Directorio Público Activo' : 'Directorio Público Desactivado'}
              </Label>
              <p className="text-sm text-muted-foreground">
                {publicDirectoryEnabled 
                  ? 'El público puede ver tu directorio de graduados en la URL configurada'
                  : 'El directorio público está desactivado y no será visible para el público'}
              </p>
            </div>
            <Switch
              id="publicDirectory"
              checked={publicDirectoryEnabled}
              onCheckedChange={async (checked) => {
                setPublicDirectoryEnabled(checked);
                // Auto-save cuando se cambia el switch
                try {
                  setSaving(true);
                  const { error } = await supabase
                    .from('companies')
                    .update({
                      public_directory_enabled: checked,
                    })
                    .eq('id', academyId);

                  if (error) throw error;

                  toast.success(checked 
                    ? 'Directorio público activado' 
                    : 'Directorio público desactivado'
                  );
                } catch (error) {
                  console.error('Error updating directory status:', error);
                  toast.error('No se pudo actualizar el estado del directorio');
                  // Revertir el cambio si falla
                  setPublicDirectoryEnabled(!checked);
                } finally {
                  setSaving(false);
                }
              }}
              disabled={saving}
            />
          </div>
        </CardContent>
      </Card>

      {/* Section 1: Personalización de Marca */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Palette className="h-5 w-5" />
            <CardTitle>Personalización de Marca</CardTitle>
          </div>
          <CardDescription>
            Configura los colores, lema y URL de tu academia para personalizar tu directorio público
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="brandColor">Color Principal</Label>
              <div className="flex gap-2">
                <Input
                  id="brandColor"
                  type="color"
                  value={brandColor}
                  onChange={(e) => setBrandColor(e.target.value)}
                  className="w-20 h-10 cursor-pointer"
                />
                <Input
                  type="text"
                  value={brandColor}
                  onChange={(e) => setBrandColor(e.target.value)}
                  placeholder="#1976d2"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="secondaryColor">Color Secundario</Label>
              <div className="flex gap-2">
                <Input
                  id="secondaryColor"
                  type="color"
                  value={secondaryColor}
                  onChange={(e) => setSecondaryColor(e.target.value)}
                  className="w-20 h-10 cursor-pointer"
                />
                <Input
                  type="text"
                  value={secondaryColor}
                  onChange={(e) => setSecondaryColor(e.target.value)}
                  placeholder="#42a5f5"
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="tagline">Lema de la Academia</Label>
            <Input
              id="tagline"
              value={tagline}
              onChange={(e) => setTagline(e.target.value)}
              placeholder="Ej: Formando el talento del futuro"
              maxLength={100}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug">URL del Directorio Público</Label>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground">app.talentodigital.io/academy/</span>
              <Input
                id="slug"
                value={academySlug}
                onChange={(e) => {
                  const newSlug = e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-+|-+$/g, '');
                  setAcademySlug(newSlug);
                }}
                placeholder={generateSlugFromName(companyName) || "mi-academia"}
              />
            </div>
            <p className="text-xs text-muted-foreground">
              La URL se genera automáticamente desde el nombre de tu academia: <span className="font-medium">{companyName}</span>
            </p>
          </div>

          <div className="flex justify-end pt-4 border-t">
            <Button onClick={handleSaveBranding} disabled={saving}>
              {saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Guardar Configuración de Marca
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Section 2: Configuración del Directorio */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Settings2 className="h-5 w-5" />
            Configuración del Directorio
          </CardTitle>
          <CardDescription>
            Personaliza qué información se muestra en tu directorio público
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <ImageIcon className="h-5 w-5 text-muted-foreground" />
              <div>
                <Label htmlFor="show-logo" className="text-sm font-medium">
                  Mostrar logo de la academia
                </Label>
                <p className="text-xs text-muted-foreground">
                  El logo aparecerá en la cabecera del directorio público
                </p>
              </div>
            </div>
            <Switch
              id="show-logo"
              checked={showLogo}
              onCheckedChange={handleToggleLogo}
              disabled={updatingDirectory}
            />
          </div>

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileText className="h-5 w-5 text-muted-foreground" />
              <div>
                <Label htmlFor="show-description" className="text-sm font-medium">
                  Mostrar descripción de la academia
                </Label>
                <p className="text-xs text-muted-foreground">
                  La descripción aparecerá debajo del logo en el directorio público
                </p>
              </div>
            </div>
            <Switch
              id="show-description"
              checked={showDescription}
              onCheckedChange={handleToggleDescription}
              disabled={updatingDirectory}
            />
          </div>

          {/* Students Filter Setting */}
          <div className="flex items-start justify-between py-3 border-t">
            <div className="flex items-start gap-3 flex-1">
              <GraduationCap className="h-5 w-5 text-muted-foreground" />
              <div className="flex-1">
                <Label className="text-sm font-medium">
                  Estudiantes a mostrar
                </Label>
                <p className="text-xs text-muted-foreground mb-2">
                  Selecciona qué estudiantes mostrar en el directorio público
                </p>
                <div className="flex gap-2 mt-2">
                  <Button
                    size="sm"
                    variant={studentsFilter === 'all' ? 'default' : 'outline'}
                    onClick={() => handleStudentsFilterChange('all')}
                    disabled={updatingDirectory}
                  >
                    Todos
                  </Button>
                  <Button
                    size="sm"
                    variant={studentsFilter === 'graduated' ? 'default' : 'outline'}
                    onClick={() => handleStudentsFilterChange('graduated')}
                    disabled={updatingDirectory}
                  >
                    Solo Graduados
                  </Button>
                  <Button
                    size="sm"
                    variant={studentsFilter === 'enrolled' ? 'default' : 'outline'}
                    onClick={() => handleStudentsFilterChange('enrolled')}
                    disabled={updatingDirectory}
                  >
                    Solo Activos
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Section 3: Vista Previa */}
      {academyData && (showLogo || showDescription) && (
        <Card>
          <CardHeader>
            <CardTitle>Vista Previa del Directorio</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 p-6 border rounded-lg bg-card">
              {showLogo && academyData.logo_url && (
                <div className="flex justify-center">
                  <img 
                    src={academyData.logo_url} 
                    alt={academyData.name}
                    className="h-20 w-auto object-contain"
                  />
                </div>
              )}
              
              <div className="text-center">
                <h3 className="text-2xl font-bold">{academyData.name}</h3>
                {showDescription && academyData.description && (
                  <p className="text-muted-foreground mt-2">
                    {academyData.description}
                  </p>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Section 4: Lista de Graduados/Estudiantes */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <GraduationCap className="h-5 w-5" />
            {studentsFilter === 'all' && `Estudiantes (${graduates.length})`}
            {studentsFilter === 'graduated' && `Graduados (${graduates.length})`}
            {studentsFilter === 'enrolled' && `Estudiantes Activos (${graduates.length})`}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {graduates.length === 0 ? (
            <div className="text-center py-8">
              <GraduationCap className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground">
                {studentsFilter === 'all' && 'No hay estudiantes en el directorio público'}
                {studentsFilter === 'graduated' && 'No hay graduados en el directorio público'}
                {studentsFilter === 'enrolled' && 'No hay estudiantes activos en el directorio público'}
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {graduates.map((graduate) => (
                <Card key={graduate.id || graduate.student_id} className="hover:shadow-md transition-shadow">
                  <CardContent className="p-4">
                    <div className="flex flex-col items-center text-center space-y-3">
                      <Avatar className="w-16 h-16">
                        <AvatarImage src={graduate.avatar_url || undefined} />
                        <AvatarFallback>
                          {graduate.full_name?.charAt(0) || 'E'}
                        </AvatarFallback>
                      </Avatar>
                      
                      <div>
                        <h3 className="font-semibold text-gray-900">
                          {graduate.full_name || graduate.student_name || 'Estudiante'}
                        </h3>
                        {graduate.location && (
                          <p className="text-sm text-gray-600 flex items-center justify-center gap-1 mt-1">
                            <MapPin className="w-3 h-3" />
                            {graduate.location}
                          </p>
                        )}
                      </div>
                      
                      {graduate.graduation_date && (
                        <div className="flex items-center gap-1 text-sm text-gray-600">
                          <Calendar className="w-3 h-3" />
                          <span>
                            Graduado: {new Date(graduate.graduation_date).toLocaleDateString()}
                          </span>
                        </div>
                      )}
                      
                      {graduate.skills && graduate.skills.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {graduate.skills.map((skill: string) => (
                            <Badge key={skill} variant="outline" className="text-xs">
                              {skill}
                            </Badge>
                          ))}
                        </div>
                      )}
                      
                      {graduate.certificate_url && (
                        <Button variant="outline" size="sm" className="w-full">
                          <ExternalLink className="h-3 w-3 mr-1" />
                          Ver Certificado
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default PublicDirectorySettings;

